version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    entrypoint: dockerize --wait tcp://app:3000 -timeout 20s ./docker-entrypoint.sh
    ports: [8080:80]
    command: ["nginx", "-g", "daemon off;"]
    expose:
      - 80
    tty: true
    depends_on:
      - app
    networks:
      - appnet

  app:
    build:
      context: ./app
    volumes:
      - ./app:/usr/local/app
    container_name: app
    depends_on:
      - db
    entrypoint: dockerize --wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    command: npm run start:dev
    tty: true
    expose:
      - 3000
    networks:
      - appnet
  db:
    container_name: db
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - appnet

networks:
  appnet:
    driver: bridge