version: '3.9'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/local/app
    image: desocupados/node-server
    container_name: app
    ports: [3000:3000]
    depends_on:
      - db
    entrypoint: dockerize --wait tcp://db:3306 -timeout 10s docker-entrypoint.sh
    command: npm run start:dev
    tty: true
    expose:
      - 3000
    networks:
      - app-network
  db:
    container_name: db
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_ROOT_PASSWORD: 123
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge